### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by QwazyWabbitWOS** [tastyspleen/r1q2-archive#1]
Trying to build r1q2ded on Linux but it fails with:
cc -DDEDICATED_ONLY -DANTICHEAT -DNDEBUG -DLINUX -O2 -fno-strict-aliasing -Wall -ffloat-store -pipe -g -MF .depends/cmd.d -MMD   -c -o cmd.o ../../qcommon/cmd.c
../../qcommon/cmd.c:1546: fatal error: opening dependency file .depends/cmd.d: No such file or directory
compilation terminated.

How exactly does one create the dependency files?

**Comment by tastyspleen** [comment]
I believe you may need to pre-create the following directories:

r1q2-archive/binaries/game/.depends
r1q2-archive/binaries/r1q2ded/.depends
r1q2-archive/binaries/client/.depends

**Comment by QwazyWabbitWOS** [comment]
Thank you, that did the trick. 
In addition, r1q2-archive/binaries/ref_gl/.depends is needed for 'make all' when building all the modules.
